"""create table conference

Revision ID: 5e5f4ad232d9
Revises: deeb8b73eed9
Create Date: 2023-03-10 09:45:55.527892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5f4ad232d9'
down_revision = 'deeb8b73eed9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.String(length=64), nullable=True),
    sa.Column('applicant', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conference_reservation')
    # ### end Alembic commands ###
